### ISSUE TITLE
download songs history

### ISSUE THREAD

**Issue by mrhussnain** [KaustubhPatange/YTPlayer#3]
please add the option of download songs history/playlist to play songs offline in app

**Comment by KaustubhPatange** [comment]
@mrhussnain I thought of this feature but of no use!

See all the songs will be downloaded to Download folder in your root storage. Now every Android device comes with a default music player which let's you listen songs on the storage! Since you already have one built in audio player app why need another one?

**Comment by mrhussnain** [comment]
yeah you are right its just my thinking lol... still thanks but some songs are not downloading can you please tell me how to solve the issue??

**Comment by KaustubhPatange** [comment]
@mrhussnain If you have any problem with failed to get a stream or download problem all issue is due to this api https://github.com/HaarigerHarald/android-youtubeExtractor so can't really fix all of them! Need to modify api code!
